experiment:
    id: kth
    embedding: resnet
    predictor: convlstm

##Data
data:
    dataset: "MMNIST"  #['MMNIST','KTH']
    seq: 20
    seed_frames: 10
    predict_frames: 10
    niters: 500

logger:
    tblogs: "tboard_logs/"   #Default path tboard_logs/DIR_NAME
    checkpoints: "checkpoints/" #Default path checkpoints/DIR_NAME

##Training
train:
    n_gpus: 1
    num_workers: 8
    max_epoch: 5
    lr: 0.0001
    batch_size: 10
    resume_point: 0  #from where to start training
    optimizer: "adam" #["adam", "rmsprop", "sgd"]
    beta1: 0.9
    scheduler: "step" #["step"]
    step_size: 10
    gamma: 0.1

architecture:
    lstm:
        mode: 'zeros' #["zeros", "random", "learned"]
        num_layers: 2
        
    skip: False

   
        