experiment:
    id: kth_2_skip
    embedding: resnet
    predictor: convlstm

##Data
data:
    dataset: "KTH"  #['MMNIST','KTH']
    seq: 20
    seed_frames: 10
    predict_frames: 10
    niters: 500

logger:
    tblogs: "tboard_logs/"   #Default path tboard_logs/DIR_NAME
    checkpoints: "checkpoints/" #Default path checkpoints/DIR_NAME

##Training
train:
    device: 2
    num_workers: 12
    max_epoch: 200
    lr: 0.0002
    batch_size: 20
    resume_point: 19  #from where to start training
    optimizer: "adam" #["adam", "rmsprop", "sgd"]
    beta1: 0.9
    scheduler: "step" 
    step_size: 50
    gamma: 0.1

architecture:
    lstm:
        mode: 'zeros' #["zeros", "random", "learned"]
        num_layers: 2
        
    skip: True
        
