experiment:
    id: mmnist_lpips_batch
    embedding: resnet
    predictor: convlstm

##Data
data:
    dataset: "MMNIST"  #['MMNIST','KTH']
    seq: 20
    seed_frames: 10
    predict_frames: 10
    niters: 2000

logger:
    tblogs: "tboard_logs/"   #Default path tboard_logs/DIR_NAME
    checkpoints: "checkpoints/" #Default path checkpoints/DIR_NAME

##Training

train:
    device: 0
    num_workers: 4
    max_epoch: 5
    lr: 0.001
    batch_size: 5
    resume_point: 0  #from where to start training
    optimizer: "adam" #["adam", "rmsprop", "sgd"]
    beta1: 0.9
    scheduler: "step" #["step"]
    step_size: 10
    gamma: 0.1
    loss: "lpips" #["mse","lpips"]

random_seed: 3292666

architecture:
    lstm:
        mode: 'zeros' #["zeros", "random", "learned"]
        num_layers: 2
        
    skip: True

   
        
