experiment:
    id: mmnist_vgg_2_skip_lpips
    embedding: vgg
    predictor: convlstm

##Data
data:
    dataset: "MMNIST"  #['MMNIST','KTH']
    seq: 20
    seed_frames: 10
    predict_frames: 10
    niters: 2000

logger:
    tblogs: "tboard_logs/"   #Default path tboard_logs/DIR_NAME
    checkpoints: "checkpoints/" #Default path checkpoints/DIR_NAME

##Training

train:
    device: 0
    num_workers: 8
    max_epoch: 100
    lr: 0.0001
    batch_size: 5
    resume_point: 0  #from where to start training
    optimizer: "adam" #["adam", "rmsprop", "sgd"]
    beta1: 0.9
    scheduler: "explr" #["step"]
    step_size: 20
    gamma: 0.9
    loss: "lpips" #["mse","lpips"]
    model_save: 10

random_seed: 3292666

architecture:
    lstm:
        mode: 'zeros' #["zeros", "random", "learned"]
        num_layers: 2
        
    skip: True
